baseURL = 'https://freemanlatrell.github.io/blog'
languageCode = 'en-us'
title = "IBM Z Modernization Blogs"
theme = 'hugo-theme-massively'
googleanalytics = "G-9MJTFHH3Y9"
disqusShortname = ""

[languages]
[languages.en]
  languageName = "English"

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"