baseURL = 'https://freemanlatrell.github.io/'
languageCode = 'en-us'
title = "Z Modernization Blogs"
theme = 'hugo-theme-massively'
googleanalytics = ""
disqusShortname = ""

[languages]
[languages.en]
  languageName = "English"

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"