baseURL = 'https://freemanlatrell.github.io/'
languageCode = 'en-us'
title = "Blogs"
theme = 'hugo-theme-massively'
googleanalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section"]

[languages]
[languages.en]
  languageName = "English"